# Generated by Django 5.2 on 2025-07-20 17:27

from django.db import migrations, models
from django.utils.timezone import now

class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_usuario_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
    ]
