# Generated by Django 5.2 on 2025-07-20 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0003_evento_actualizado_en_evento_creado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivorequisito',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Eventos.inscripcion'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Eventos.inscripcion'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='inscripcion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Eventos.inscripcion'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_organizados', to='Eventos.usuario'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Eventos.evento'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Eventos.usuario'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Eventos.usuario'),
        ),
    ]
